server:
  port: 8769

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: service-graphite
  sleuth:
    sampler:
      percentage: 1.0

management:
  security:
    enabled: false

logging:
  file: "service.log"
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: DEBUG
